services:
  teos-ban-api:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      AWS_REGION: us-east-1
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"