spring:
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password: ""
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true
        console.path: /h2-console
        console.settings.trace: false 
        console.settings.web-allow-others: false

ban:
    teo:
        redirect_uris: "http://localhost:3000"
        allowed_origins: "http://localhost:3000"
        redis:
            host: localhost

cloud:
    aws:
        credentials:
            profile-name: default
        s3:
            bucketName: teos-test-bucket-457125958973
            region: us-east-1

logging:
    level:
        org:
            springframework:
                web: DEBUG