spring:
    profiles:
        active: dev
    cache:
        type: redis
        port: 6379
    data:
        redis:
            repositories:
                type: none
    jpa:
      properties:
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: create.sql

cloud:
    aws:
        regionName: us-east-1
        secrets:
          secretName: twitch/app
        s3:
            fileBasePath: "v1/teosban/appeal/"

server:
    port: 8080
    servlet:
        context-path: "/v1/teosban"
        session:
          timeout: 30m
          cookie:
            max-age: 30m

twitch:
    url:
        auth: "https://id.twitch.tv/oauth2/token"
        userinfo: "https://id.twitch.tv/oauth2/userinfo"
        keys: "https://id.twitch.tv/oauth2/keys"
        issuer: "https://id.twitch.tv/oauth2"
        validate: "https://id.twitch.tv/oauth2/validate"

ban:
    teo:
        roles:
            ADMIN:
            - teosgame
            - hobocutie
            - markvs
            - rushthetoastyboi
            DEVELOPER:
            - rushthetoastyboi