spring:
    datasource:
        dbName: bandb
        driverClassName: com.mysql.jdbc.Driver

ban:
    teo:
        redirect_uris: "https://teos-ban-appeals.com"
        allowed_origins: "https://teos-ban-appeals.com"
        redis:
            host: redis

cloud:
    aws:
        s3:
            bucketName: teos-prod-bucket-457125958973