spring:
    profiles:
        active: dev

server:
    port: 8080
    servlet:
        context-path: "/v1/teosban"

twitch:
    url:
        auth: "https://id.twitch.tv/oauth2/token"
        userinfo: "https://id.twitch.tv/oauth2/userinfo"
        keys: "https://id.twitch.tv/oauth2/keys"
        issuer: "https://id.twitch.tv/oauth2"

ban:
    teo:
        roles:
            TEO: teosgame
            ADMIN:
            - hobocutie
            - markvs
            DEVELOPER:
            - rushthetoastyboi