spring:
    profiles:
        active: dev
    cache:
        type: redis
        port: 6379

server:
    port: 8080
    servlet:
        context-path: "/v1/teosban"

twitch:
    url:
        auth: "https://id.twitch.tv/oauth2/token"
        userinfo: "https://id.twitch.tv/oauth2/userinfo"
        keys: "https://id.twitch.tv/oauth2/keys"
        issuer: "https://id.twitch.tv/oauth2"
        validate: "https://id.twitch.tv/oauth2/validate"

ban:
    teo:
        roles:
            ADMIN:
            - teosgame
            - hobocutie
            - markvs
            DEVELOPER:
            - rushthetoastyboi