ban:
    teo:
        redirect_uris: "http://localhost:3000"
        allowed_origins: "http://localhost:3000"
        redis:
            host: localhost

logging:
    level:
        org:
            springframework:
                web: DEBUG