spring:
    profiles:
        active: dev

server:
    port: 8080
    servlet:
        context-path: "/v1/teosban"

twitch:
    url:
        auth: "https://id.twitch.tv/oauth2/token"
        userinfo: "https://api.twitch.tv/helix/users"